<?php

//PSR-4 compliant autoloader. I could have used the autoloader generated by Composer.

spl_autoload_register(function ($class) {

    $prefix = 'Cenoura\\';
    $baseDir = __DIR__ . DIRECTORY_SEPARATOR;

    $prefixLength = strlen($prefix);

    if (strncmp($prefix, $class, $prefixLength) !== 0) {
        return;
    }

    $relativeClassName = substr($class, $prefixLength);

    $filePath = $baseDir . str_replace('\\', DIRECTORY_SEPARATOR, $relativeClassName) . '.php';

    if (file_exists($filePath)) {
        require $filePath;
    }
});
